[generate_validation_site_list]
count = 5000
output = "var/generated/validation_sites.txt"

[scrape_edinet_reports]
skip_existing = true
headless = false
disable_xvfb = true

[parse_xbrl_financials]
skip_existing = true

[scrape_stooq_prices]
pool_size = 1
headless = false
disable_xvfb = true
output_dir = "var/raw/stooq"

[scrape_yahoo_finance_prices]
pool_size = 1
headless = false
disable_xvfb = true

[scrape_edinet_historical]
skip_existing = true
years = 10
